#!/usr/bin/env bash
# name_watchlist_search.sh — search the FTS5 transcript/document index for N names
#
# Usage:
#   ./name_watchlist_search.sh --db /path/to/bonfyre.db --names names.txt [--out report.md]
#
# Input: names.txt — one name per line (e.g. "John Doe", "Jane Smith")
# Output: Markdown hit report, one section per name, with doc/page/context
#
# The Akai FTS5 index schema assumed:
#   CREATE VIRTUAL TABLE docs_fts USING fts5(
#       doc_id, source_file, page_num, text,
#       tokenize='porter unicode61'
#   );
#
# If you haven't indexed yet, run:
#   akai-index --corpus /path/to/corpus --db /path/to/bonfyre.db

set -euo pipefail

DB=""
NAMES_FILE=""
OUT_FILE="-"
MAX_CONTEXT_CHARS=300
MIN_HITS_TO_REPORT=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --db)      DB="$2"; shift 2 ;;
    --names)   NAMES_FILE="$2"; shift 2 ;;
    --out)     OUT_FILE="$2"; shift 2 ;;
    --context) MAX_CONTEXT_CHARS="$2"; shift 2 ;;
    *) echo "unknown: $1"; exit 1 ;;
  esac
done

[[ -z "$DB" ]]         && { echo "need --db"; exit 1; }
[[ -z "$NAMES_FILE" ]] && { echo "need --names"; exit 1; }
[[ -f "$DB" ]]         || { echo "db not found: $DB"; exit 1; }
[[ -f "$NAMES_FILE" ]] || { echo "names file not found: $NAMES_FILE"; exit 1; }

command -v sqlite3 &>/dev/null || { echo "sqlite3 not found"; exit 1; }

# ── read names (bash 3.2 compatible) ─────────────────────────────────────────
NAMES=()
while IFS= read -r line; do
  line="$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  [[ -z "$line" ]] && continue
  NAMES+=("$line")
done < "$NAMES_FILE"
TOTAL_NAMES=${#NAMES[@]}
TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

# ── output buffer ─────────────────────────────────────────────────────────────
REPORT=""

header() {
  REPORT+="# Name Watchlist Search Report

**Database**: \`${DB}\`
**Watchlist**: \`${NAMES_FILE}\` (${TOTAL_NAMES} names)
**Generated**: ${TIMESTAMP}

---

## Summary Table

| Name | Hits | Top Document |
|---|---|---|
"
}

footer() {
  REPORT+="
---
_Generated by name_watchlist_search.sh_
"
}

header

# ── per-name FTS5 query ───────────────────────────────────────────────────────
DETAIL_SECTION=""
SUMMARY_ROWS=""

for name in "${NAMES[@]}"; do
  # escape single quotes for SQLite
  safe_name="${name//\'/\'\'}"

  # FTS5 phrase query: wrap multi-word names in quotes
  word_count=$(echo "$name" | wc -w | tr -d ' ')
  if [[ $word_count -gt 1 ]]; then
    fts_query="\"${safe_name}\""
  else
    fts_query="${safe_name}"
  fi

  # Count hits
  hit_count=$(sqlite3 "$DB" \
    "SELECT COUNT(*) FROM docs_fts WHERE docs_fts MATCH '${fts_query}';" 2>/dev/null || echo 0)

  top_doc="—"

  if [[ $hit_count -ge $MIN_HITS_TO_REPORT ]]; then
    # Top document
    top_doc=$(sqlite3 "$DB" \
      "SELECT source_file, COUNT(*) AS c
       FROM docs_fts
       WHERE docs_fts MATCH '${fts_query}'
       GROUP BY source_file
       ORDER BY c DESC LIMIT 1;" 2>/dev/null | awk -F'|' '{print $1}' | head -1 || echo "(unknown)")

    # Fetch up to 10 snippet hits
    snippets=$(sqlite3 "$DB" \
      "SELECT source_file, page_num,
              snippet(docs_fts, 3, '**', '**', '…', 20)
       FROM docs_fts
       WHERE docs_fts MATCH '${fts_query}'
       ORDER BY rank
       LIMIT 10;" 2>/dev/null || true)

    DETAIL_SECTION+="### ${name}

**Hits**: ${hit_count} | **Top doc**: \`${top_doc}\`

| Document | Page | Snippet |
|---|---|---|
"
    while IFS='|' read -r doc pg snip; do
      [[ -z "$doc" ]] && continue
      DETAIL_SECTION+="| \`${doc}\` | ${pg} | ${snip} |
"
    done <<< "$snippets"

    DETAIL_SECTION+="
"
  else
    top_doc="—"
  fi

  SUMMARY_ROWS+="| ${name} | ${hit_count} | \`${top_doc}\` |
"
done

REPORT+="${SUMMARY_ROWS}"

REPORT+="
---

## Per-Name Detail

${DETAIL_SECTION}"

footer

# ── output ────────────────────────────────────────────────────────────────────
if [[ "$OUT_FILE" == "-" ]]; then
  echo "$REPORT"
else
  echo "$REPORT" > "$OUT_FILE"
  echo "Report written to $OUT_FILE" >&2
fi
